# Screen settings
screen_width: 750
screen_height: 570
bg_colour: [200, 200, 200]
fps: 60

# Paddle settings
paddle_width: 330
paddle_height: 40
paddle_colour: [0, 255, 0]
paddle_speed: 35

# Ball settings
ball_width: 50
ball_height: 50
ball_colour: [0, 0, 0]
ball_speed: 6
speed_up_factor: 1.05

# Game settings
total_lives: 3

# Connection settings
server_host: "localhost"
server_port: 5555
